% Define the training set
categories = {...
    'NE_MAIN_S', 'NE_MAIN_W', 'NW_MAIN_E', 'NW_MAIN_S',...
    'SE_MAIN_N', 'SE_MAIN_W', 'SW_MAIN_E', 'SW_MAIN_N',...
    'NE_SELF_S', 'NE_SELF_W', 'NW_SELF_E', 'NW_SELF_S',...
    'SE_SELF_N', 'SE_SELF_W', 'SW_SELF_E', 'SW_SELF_N'...
};
% q_categories = {...
%     'NE_MAIN_W', 'NW_MAIN_E', 'NW_MAIN_S',...
%     'SW_MAIN_E',...
%     'NE_SELF_W', 'NW_SELF_E', 'NW_SELF_S',...
%     'SW_SELF_E'...
% };
trainingSet = imageDatastore(fullfile('trainingImages', categories),...
    'LabelSource', 'foldernames');
validationSet = imageDatastore(fullfile('questionImages', categories),...
    'LabelSource', 'foldernames');
nightValidationSet = imageDatastore(fullfile('nightImages', categories),...
    'LabelSource', 'foldernames');

% Show two sample images
subplot(1,2,1);
imshow(readimage(trainingSet, 1))
subplot(1,2,2);
imshow(readimage(trainingSet, 9))

% Create a bag of features and a classifier
bag = bagOfFeatures(trainingSet);
categoryClassifier = trainImageCategoryClassifier(trainingSet, bag);

% Make a confusion matrix from the question images!
confMatrix = evaluate(categoryClassifier, validationSet);
nightConfMatrix = evaluate(categoryClassifier, nightValidationSet);

